<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jv_ranking"
 *
 * Auto generated by Extension Builder 2019-07-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['jv_ranking'] = [
    'title' => 'JV Ranking Module',
    'description' => 'Sort Organizer by options list',
    'category' => 'plugin',
    'author' => 'Amerigo Velletti',
    'author_email' => 'typo3@velletti.de',
    'state' => 'beta',
    'clearCacheOnLoad' => true,
    'version' => '12.4.3',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
            'jv_events' => '^12.4',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
