<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jv_ranking"
 *
 * Auto generated by Extension Builder 2019-07-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'JV Ranking Module',
    'description' => 'Sort Vorganizer by options list',
    'category' => 'plugin',
    'author' => 'Amerigo Velletti',
    'author_email' => 'typo3@velletti.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '10.4.1',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
